@echo off
echo Starting F-EARN Application...

echo Starting Backend Server...
start cmd /k "cd Backend && npm run dev"

echo Starting Frontend Server...
start cmd /k "cd Frontend && npm start"

echo Servers are starting...
echo Backend will be available at: http://localhost:5000
echo Frontend will be available at: http://localhost:3000 